const topColleges = [
  {
    id: "#1",
    thumb: "https://seeklogo.com/images/M/MIT-logo-73A348B3DB-seeklogo.com.png",
    collegeName: "Massachusetts Institute of Technology (MIT)",
    collegeAddress: "Cambridge, MA, USA",
    feature: true,
    subject: "Biomedical Sciences",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$89,000",
    placementRate: 90,
    userReview: "9.9/10",
    reviewBase: "Based on 800 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#1 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#2",
    thumb: "https://2010.igem.org/wiki/images/5/57/Caltech_logo_watermark.png",
    collegeName: "California Institute of Technology (Caltech)",
    collegeAddress: "Pasadena, CA, USA",
    feature: false,
    subject: "Computer Science (CS)",
    courseFee: "$90,000",
    maxiSalary: "$120,000",
    miniSalary: "$100,000",
    placementRate: 78,
    userReview: "9.2/10",
    reviewBase: "Based on 789 user reviews",
    reviewbtn: "Best in Learning",
    ranking: "#2 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#3",
    thumb:
      "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/qm5x2rgrgjoj0gz3n2pj",
    collegeName: "Harvard University",
    collegeAddress: "Cambridge, MA, USA",
    feature: false,
    subject: "Archaeology and Anthropology",
    courseFee: "$93,000",
    maxiSalary: "$88,000",
    miniSalary: "$75,000",
    placementRate: 45,
    userReview: "9.8/10",
    reviewBase: "Based on 784 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#3 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#4",
    thumb:
      "https://bitcoinproject.files.wordpress.com/2011/06/stanford_seal_256.png",
    collegeName: "Stanford University",
    collegeAddress: "Stanford, CA, USA",
    feature: true,
    subject: "Applied Physics (APPPHYS)",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$110,000",
    placementRate: 98,
    userReview: "8.9/10",
    reviewBase: "Based on 599 user reviews",
    reviewbtn: "Best in Learning",
    ranking: "#4 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#5",
    thumb:
      "https://trexquant.com/_next/image?url=%2FSchoolLogos%2FPrinceton-Medium.png&w=3840&q=75",
    collegeName: "Princeton University",
    collegeAddress: "Princeton, NJ, USA",
    feature: false,
    subject: "Biology/Hopkins Marine",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$110,000",
    placementRate: 98,
    userReview: "9.2/10",
    reviewBase: "Based on 676 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#5 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#6",
    thumb:
      "https://insights.som.yale.edu/themes/custom/insights/assets/dist/images/favicon-som-256x256.png",
    collegeName: "Yale University",
    collegeAddress: "New Haven, CT, USA",
    feature: false,
    subject: "Mathematics and Statistics",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$110,000",
    placementRate: 98,
    userReview: "8.0/10",
    reviewBase: "Based on 400 user reviews",
    reviewbtn: "Best in Learning",
    ranking: "#6 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#7",
    thumb:
      "https://seeklogo.com/images/U/university-of-chicago-logo-0F38E68A5B-seeklogo.com.png",
    collegeName: "University of Chicago",
    collegeAddress: "Chicago, IL, USA",
    feature: false,
    subject: "History and Modern Languages",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$110,000",
    placementRate: 98,
    userReview: "9.5/10",
    reviewBase: "Based on 301 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#7 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#8",
    thumb:
      "https://p3.itc.cn/q_70/images03/20220108/92292a3d2033465ab59844fcd3700fb1.png",
    collegeName: "Columbia University",
    collegeAddress: "New York City, NY, USA",
    feature: true,
    courseFee: "$93,000",
    subject: "Law (Jurisprudence)",
    miniSalary: "$110,000",
    maxiSalary: "$150,000",
    placementRate: 98,
    userReview: "8.8/10",
    featured: "false",
    reviewBase: "Based on 239 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#8 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#9",
    thumb:
      "https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/University_of_Texas_at_Austin_seal.svg/1200px-University_of_Texas_at_Austin_seal.svg.png",
    collegeName: "University of Texas at Austin",
    collegeAddress: "2515 Speedway, Austin, TX 78712, USA",
    feature: false,
    courseFee: "$93,000",
    subject: "Theology and Religion",
    miniSalary: "$110,000",
    maxiSalary: "$100,000",
    placementRate: 98,
    userReview: "9.7/10",
    reviewBase: "Based on 289 user reviews",
    reviewbtn: "Best in Learning",
    ranking: "#9 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#10",
    thumb: "https://ymgrad.com/media/logo/cornell.png",
    collegeName: " Cornell University",
    collegeAddress: "Ithaca, NY 14850, United States",
    feature: false,
    subject: "Economics and Management",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$110,000",
    placementRate: 98,
    userReview: "9.2/10",
    reviewBase: "Based on 689 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#10 out of 120 Colleges/Universities of the world",
  },
];

export default topColleges;
