const topColleges = [
  {
    id: "#1",
    thumb: "https://example.com/mit_thumb.jpg",
    collegeName: "Massachusetts Institute of Technology (MIT)",
    collegeAddress: "Cambridge, MA, USA",
    feature: true,
    subject: "Biomedical Sciences",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$89,000",
    placementRate: 90,
    userReview: "9.9/10",
    reviewBase: "Based on 800 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#1 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#2",
    thumb: "https://example.com/caltech_thumb.jpg",
    collegeName: "California Institute of Technology (Caltech)",
    collegeAddress: "Pasadena, CA, USA",
    feature: false,
    subject: "Computer Science (CS)",
    courseFee: "$90,000",
    maxiSalary: "$120,000",
    miniSalary: "$100,000",
    placementRate: 78,
    userReview: "9.2/10",
    reviewBase: "Based on 789 user reviews",
    reviewbtn: "Best in Learning",
    ranking: "#2 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#3",
    thumb: "https://example.com/harvard_thumb.jpg",
    collegeName: "Harvard University",
    collegeAddress: "Cambridge, MA, USA",
    feature: false,
    subject: "Archaeology and Anthropology",
    courseFee: "$93,000",
    maxiSalary: "$88,000",
    miniSalary: "$75,000",
    placementRate: 45,
    userReview: "9.8/10",
    reviewBase: "Based on 784 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#3 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#4",
    thumb: "https://example.com/stanford_thumb.jpg",
    collegeName: "Stanford University",
    collegeAddress: "Stanford, CA, USA",
    feature: true,
    subject: "Applied Physics (APPPHYS)",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$110,000",
    placementRate: 98,
    userReview: "8.9/10",
    reviewBase: "Based on 599 user reviews",
    reviewbtn: "Best in Learning",
    ranking: "#4 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#5",
    thumb: "https://example.com/princeton_thumb.jpg",
    collegeName: "Princeton University",
    collegeAddress: "Princeton, NJ, USA",
    feature: false,
    subject: "Biology/Hopkins Marine",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$110,000",
    placementRate: 98,
    userReview: "9.2/10",
    reviewBase: "Based on 676 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#5 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#6",
    thumb: "https://example.com/yale_thumb.jpg",
    collegeName: "Yale University",
    collegeAddress: "New Haven, CT, USA",
    feature: false,
    subject: "Mathematics and Statistics",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$110,000",
    placementRate: 98,
    userReview: "8.0/10",
    reviewBase: "Based on 400 user reviews",
    reviewbtn: "Best in Learning",
    ranking: "#6 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#7",
    thumb: "https://example.com/chicago_thumb.jpg",
    collegeName: "University of Chicago",
    collegeAddress: "Chicago, IL, USA",
    feature: false,
    subject: "History and Modern Languages",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$110,000",
    placementRate: 98,
    userReview: "9.5/10",
    reviewBase: "Based on 301 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#7 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#8",
    thumb: "https://example.com/columbia_thumb.jpg",
    collegeName: "Columbia University",
    collegeAddress: "New York City, NY, USA",
    feature: true,
    courseFee: "$93,000",
    subject: "Law (Jurisprudence)",
    miniSalary: "$110,000",
    maxiSalary: "$150,000",
    placementRate: 98,
    userReview: "8.8/10",
    featured: "false",
    reviewBase: "Based on 239 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#8 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#9",
    thumb: "https://example.com/penn_thumb.jpg",
    collegeName: "University of Pennsylvania",
    collegeAddress: "Philadelphia, PA, USA",
    feature: false,
    courseFee: "$93,000",
    subject: "Theology and Religion",
    miniSalary: "$110,000",
    maxiSalary: "$100,000",
    placementRate: 98,
    userReview: "9.7/10",
    reviewBase: "Based on 289 user reviews",
    reviewbtn: "Best in Learning",
    ranking: "#9 out of 120 Colleges/Universities of the world",
  },
  {
    id: "#10",
    thumb: "https://example.com/oxford_thumb.jpg",
    collegeName: "University of Oxford",
    collegeAddress: "Oxford, England",
    feature: false,
    subject: "Economics and Management",
    courseFee: "$93,000",
    maxiSalary: "$150,000",
    miniSalary: "$110,000",
    placementRate: 98,
    userReview: "9.2/10",
    reviewBase: "Based on 689 user reviews",
    reviewbtn: "Best in Social Life",
    ranking: "#10 out of 120 Colleges/Universities of the world",
  },
];

export default topColleges;
