const topColleges = [
  {
    id: "#1",
    thumb: "https://example.com/mit_thumb.jpg",
    collegeName: "Massachusetts Institute of Technology (MIT)",
    collegeAddress: "Cambridge, MA, USA",
    courseFee: "$93000",
    highestSalary: "$150000",
    lowestSalary: "$89000",
    placementRate: 98,
    userReview: "9.9/10",

    ranking: 1,
  },
  {
    id: "#2",
    thumb: "https://example.com/caltech_thumb.jpg",
    collegeName: "California Institute of Technology (Caltech)",
    collegeAddress: "Pasadena, CA, USA",
    courseFee: "$90000",
    highestSalary: "$120000",
    mediumSalary: "$100000",
    placementRate: 89,
    userReview: "9.2/10",

    ranking: 2,
  },
  {
    id: "#3",
    thumb: "https://example.com/harvard_thumb.jpg",
    collegeName: "Harvard University",
    collegeAddress: "Cambridge, MA, USA",
    courseFee: "$93000",
    highestSalary: "$88000",
    mediumSalary: "$75000",
    placementRate: 98,
    userReview: "9.8/10",
    ranking: 3,
  },
  {
    id: "#4",
    thumb: "https://example.com/stanford_thumb.jpg",
    collegeName: "Stanford University",
    collegeAddress: "Stanford, CA, USA",
    courseFee: "$93000",
    highestSalary: "$150000",
    lowestSalary: "$110000",
    placementRate: 98,
    userReview: "8.9/10",
    feature: "featured",
    ranking: 4,
  },
  {
    id: "#5",
    thumb: "https://example.com/princeton_thumb.jpg",
    collegeName: "Princeton University",
    collegeAddress: "Princeton, NJ, USA",
    courseFee: "$93000",
    highestSalary: "$150000",
    lowestSalary: "$110000",
    placementRate: 98,
    userReview: "9.2/10",

    ranking: 5,
  },
  {
    id: "#6",
    thumb: "https://example.com/yale_thumb.jpg",
    collegeName: "Yale University",
    collegeAddress: "New Haven, CT, USA",
    courseFee: "$93000",
    highestSalary: "$150000",
    lowestSalary: "$110000",
    placementRate: 98,
    userReview: "8.0/10",

    ranking: 6,
  },
  {
    id: "#7",
    thumb: "https://example.com/chicago_thumb.jpg",
    collegeName: "University of Chicago",
    collegeAddress: "Chicago, IL, USA",
    courseFee: "$93000",
    highestSalary: "$150000",
    lowestSalary: "$110000",
    placementRate: 98,
    userReview: "9.5/10",

    ranking: 7,
  },
  {
    id: "#8",
    thumb: "https://example.com/columbia_thumb.jpg",
    collegeName: "Columbia University",
    collegeAddress: "New York City, NY, USA",
    courseFee: "$93000",
    lowestSalary: "$110000",
    highestSalary: "$150000",
    placementRate: 98,
    userReview: "8.8/10",
    featured: "false",
    ranking: 8,
  },
  {
    id: "#9",
    thumb: "https://example.com/penn_thumb.jpg",
    collegeName: "University of Pennsylvania",
    collegeAddress: "Philadelphia, PA, USA",
    courseFee: "$93000",
    lowestSlary: "$110000",
    highestSalary: "$150000",
    placementRate: 98,
    userReview: "9.7/10",
    ranking: 9,
  },
  {
    id: "#10",
    thumb: "https://example.com/oxford_thumb.jpg",
    collegeName: "University of Oxford",
    collegeAddress: "Oxford, England",
    courseFee: "$93000",
    highestSalary: "$150000",
    lowestSlary: "$110000",
    placementRate: 98,
    userReview: "9.2/10",

    ranking: 10,
  },
];

export default topColleges;
